name: Release Management
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - reopened
  milestone:
    types:
      - closed
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  release-managment:
    name: Release Management
    uses: WyriHaximus/github-workflows/.github/workflows/package-release-managment.yaml@github-actions-workflows
    with:
      milestone: ${{ github.event.milestone.title }}
      description: ${{ github.event.milestone.title }}
